name: CI Build

on:
  push:
    branches: [ test* ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run go tests
        run: cd src && go test ./...
